// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTXr-UCrJMYODXwbyFbcYNJqIHBGxT_Lc',
    appId: '1:665229138707:web:54c3b7e758cf6f93c898e6',
    messagingSenderId: '665229138707',
    projectId: 'ettaskmanager',
    authDomain: 'ettaskmanager.firebaseapp.com',
    storageBucket: 'ettaskmanager.appspot.com',
    measurementId: 'G-2NM13C2X2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzqGd7pvaxbXpB3pXd8QZH5pXjz_Py1EI',
    appId: '1:665229138707:android:a7873c12f376b3b8c898e6',
    messagingSenderId: '665229138707',
    projectId: 'ettaskmanager',
    storageBucket: 'ettaskmanager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt5xNFNN_ubJH-xHA0AAVu2L5LhGXx5Mg',
    appId: '1:665229138707:ios:e05a0fc5366638d8c898e6',
    messagingSenderId: '665229138707',
    projectId: 'ettaskmanager',
    storageBucket: 'ettaskmanager.appspot.com',
    iosBundleId: 'com.ett99it.ettaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt5xNFNN_ubJH-xHA0AAVu2L5LhGXx5Mg',
    appId: '1:665229138707:ios:e05a0fc5366638d8c898e6',
    messagingSenderId: '665229138707',
    projectId: 'ettaskmanager',
    storageBucket: 'ettaskmanager.appspot.com',
    iosBundleId: 'com.ett99it.ettaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTXr-UCrJMYODXwbyFbcYNJqIHBGxT_Lc',
    appId: '1:665229138707:web:a0e96af09d72ee26c898e6',
    messagingSenderId: '665229138707',
    projectId: 'ettaskmanager',
    authDomain: 'ettaskmanager.firebaseapp.com',
    storageBucket: 'ettaskmanager.appspot.com',
    measurementId: 'G-QX4E62GJTX',
  );
}
